logging:
  level:
    root: INFO
    com:
      google:
        cloud:
          firestore:
            CustomClassMapper: ERROR
            encoding:
              PojoBeanMapper: ERROR
server:
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: /rest
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /documentation.html
spring:
  mvc:
    format:
      date: yyyy-MM-dd
management:
  endpoints:
    web:
      exposure:
        include:
          - loggers
          - health
          - metrics
  endpoint:
    loggers:
      access: read_only
    health:
      access: read_only
    metrics:
      access: read_only
config:
  personalEntries:
    start: 5
    end: 90
  personalStarts:
    start: 5
    end: 90
  personalResults:
    start: 90
    end: 5