name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write  # allow pushing to GHCR

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: maven
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        if: ${{ steps.release.outputs.release_created }}
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/eventor-api
          IMAGE_TAG: ${{ steps.release.outputs.tag_name }}
        run: |
          echo "Building image $IMAGE_NAME:$IMAGE_TAG"
          docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest
      - name: Output Published Image References
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "Published: ghcr.io/${{ github.repository_owner }}/eventor-api:${{ steps.release.outputs.tag_name }}"
          echo "Published: ghcr.io/${{ github.repository_owner }}/eventor-api:latest"
